/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import BN from "bn.js";
import { ContractOptions } from "web3-eth-contract";
import { EventLog } from "web3-core";
import { EventEmitter } from "events";
import {
  Callback,
  PayableTransactionObject,
  NonPayableTransactionObject,
  BlockType,
  ContractEventLog,
  BaseContract,
} from "./types";

export interface EventOptions {
  filter?: object;
  fromBlock?: BlockType;
  topics?: string[];
}

export type MetaTransactionExecuted = ContractEventLog<{
  userAddress: string;
  relayerAddress: string;
  functionSignature: string;
  0: string;
  1: string;
  2: string;
}>;
export type OwnershipTransferred = ContractEventLog<{
  previousOwner: string;
  newOwner: string;
  0: string;
  1: string;
}>;

export interface RabbitCatchMaster extends BaseContract {
  constructor(
    jsonInterface: any[],
    address?: string,
    options?: ContractOptions
  ): RabbitCatchMaster;
  clone(): RabbitCatchMaster;
  methods: {
    baseURI(): NonPayableTransactionObject<string>;

    canMint(_for: string): NonPayableTransactionObject<boolean>;

    czodiacNFT(): NonPayableTransactionObject<string>;

    executeMetaTransaction(
      userAddress: string,
      functionSignature: string | number[],
      sigR: string | number[],
      sigS: string | number[],
      sigV: number | string | BN
    ): PayableTransactionObject<string>;

    getNonce(user: string): NonPayableTransactionObject<string>;

    getPrice(): NonPayableTransactionObject<string>;

    mint(_for: string, _code: string): PayableTransactionObject<void>;

    mintCount(): NonPayableTransactionObject<string>;

    mintCountMax(): NonPayableTransactionObject<string>;

    mintCountPriceIncrement(): NonPayableTransactionObject<string>;

    owner(): NonPayableTransactionObject<string>;

    priceIncrement(): NonPayableTransactionObject<string>;

    priceStart(): NonPayableTransactionObject<string>;

    rabbitBreed(): NonPayableTransactionObject<string>;

    rabbitCreed(): NonPayableTransactionObject<string>;

    rabbitFancier(): NonPayableTransactionObject<string>;

    rabbitGreed(): NonPayableTransactionObject<string>;

    rabbitRocket(): NonPayableTransactionObject<string>;

    renounceOwnership(): NonPayableTransactionObject<void>;

    transferOwnership(newOwner: string): NonPayableTransactionObject<void>;

    updateWhitelist(
      _addr: string,
      _val: boolean
    ): NonPayableTransactionObject<void>;

    whitelist(arg0: string): NonPayableTransactionObject<boolean>;

    whitelistMintCap(): NonPayableTransactionObject<string>;
  };
  events: {
    MetaTransactionExecuted(
      cb?: Callback<MetaTransactionExecuted>
    ): EventEmitter;
    MetaTransactionExecuted(
      options?: EventOptions,
      cb?: Callback<MetaTransactionExecuted>
    ): EventEmitter;

    OwnershipTransferred(cb?: Callback<OwnershipTransferred>): EventEmitter;
    OwnershipTransferred(
      options?: EventOptions,
      cb?: Callback<OwnershipTransferred>
    ): EventEmitter;

    allEvents(options?: EventOptions, cb?: Callback<EventLog>): EventEmitter;
  };

  once(
    event: "MetaTransactionExecuted",
    cb: Callback<MetaTransactionExecuted>
  ): void;
  once(
    event: "MetaTransactionExecuted",
    options: EventOptions,
    cb: Callback<MetaTransactionExecuted>
  ): void;

  once(event: "OwnershipTransferred", cb: Callback<OwnershipTransferred>): void;
  once(
    event: "OwnershipTransferred",
    options: EventOptions,
    cb: Callback<OwnershipTransferred>
  ): void;
}
